### PR TITLE
[fix](cache) small code changes / doc / vars name / pattern matching

### PR DESCRIPTION
**Pull request by areski**
After reading the code and wanted to mess it around!
Sorry for the bikeshedding here, found that you used suffix when calling the code and then used postfix strange, plus a couple of changes, hopefully some time it helps to have an other pair of eyes looking at things.

BTW great job on the simple cache, definitely better than heaving a big dependencies when we needed something simple. I was going to tackle that but you are just too fast :)

### CODE REVIEW

**Comment by aesmail** [comment]
I'm glad you did. These changes definitely improve the code. I'm merging this, but what's the  reason for the `@moduledoc`? Usually `@moduledoc`s are added if the module is going to be used by other users. If it's for internal documentation, I recommend using `@moduledoc false` at the top and keep the existing function `@doc`s. If it *is* for external users, I'm interested in knowing the reasons/use-cases.

**Comment by areski** [comment]
I thought that `@moduledoc` is to add a general documentation about the module and describe what the module does, at the contrary `@doc` is used to document the behaviour of a function only
https://hexdocs.pm/elixir/writing-documentation.html

The idea what to give a small overview for other developer to understand quickly what each module intend to do. You have more experience that me, so feel free to correct this.

That also bring me to an other issue I wanted to open, I think the code could use a bit more of self documentation :smile:

**Comment by aesmail** [comment]
Documentation is extremely important. But I feel it slows the progress down especially when things change too quickly. I have 2 issues open for documentation and testing. Once v0.8 is released, one of the main priorities is to add new code typespecs and docs. Adding unit tests with typespecs will hugely make things easier to understand the would catch more bugs more quickly with dialyzer.

But, going back to the original question, defining `@moduledoc` would add the module to the public documentation which in this case doesn't make sense since `Kaffy.Cache.Table` and the like are only used internally by Kaffy (check [this section](https://hexdocs.pm/elixir/writing-documentation.html#hiding-internal-modules-and-functions) of the elixir docs).

**Comment by areski** [comment]
I will totally agree with you, let's focus on doc & test when we get to a level where things stop moving so quickly. It would certainly slow things down if we do that too early and that would be counter productive.

Thanks for the link on `@moduledoc`, I see your point now and it makes sense

**Comment by aesmail** [comment]
btw, I would love some help in documenting and adding tests typespecs.

Currently, the only module that needs `@moduledoc` is `Kaffy.ResourceAdmin` since it has all the functions a user could overload to get customized behavior.

I'd appreciate some help with testing and documenting the rest of the code too.

**Comment by areski** [comment]
Will try to help with it when the time comes for us to focus on it.
Right now, I'm working on a datetime picker which is taking me forever, but the PR is coming soon :)

**Comment by aesmail** [comment]
Ah! That's awesome! The current date/time select boxes are so ugly.

**Pull request merged**
