### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by drobban**
related to issue #258

### CODE REVIEW

**Comment by ghenry** [comment]
I'm not sure if anyone is maintaining this anymore? I opened an issue to offer to help. Thanks for doing a PR.

**Comment by drobban** [comment]
kind of weird, I wonder if something has happened to aesmail. He were very active for not so long time ago.

His account seems to be very active in private repos, perhaps he has a bit high workload at the moment.

**Comment by maysam** [comment]
@drobban he probably got a job

**Comment by drobban** [comment]
> @drobban he probably got a job

=) probably.

**Comment by ali-kogni** [comment]
pr working for me

**Comment by drobban** [comment]
> pr working for me

Thanks for reporting back - I guess its valuable @aesmail to know the information is correct

**Pull request merged**
