### PR TITLE
add a default "delete selected records" action

### PR DESCRIPTION
**Pull request by aesmail**
This PR adds a default action to the resource index page for deleting selected records.

### CODE REVIEW

**Comment by aesmail** [comment]
This needs to take into consideration whether the `delete` action is [enabled or not](https://github.com/aesmail/kaffy/blob/c455505d4d20c957271c1176f9068e453c13a60d/lib/kaffy/resource_admin.ex#L137).

**Comment by ghenry** [comment]
> This needs to take into consideration whether the `delete` action is [enabled or not](https://github.com/aesmail/kaffy/blob/c455505d4d20c957271c1176f9068e453c13a60d/lib/kaffy/resource_admin.ex#L137).

Is this good now?

**Comment by aesmail** [comment]
This still needs to check whether `:delete` exists or not. I will add the check today and push the changes.

**Comment by aesmail** [comment]
Closing this. It has been implemented in another PR.

**Pull request closed without merging**
