### PR TITLE
update phx to 1.6.6

### PR DESCRIPTION
**Pull request by arturictus**

### CODE REVIEW

**Comment by vermaxik** [comment]
@arturictus  thanks a lot for your contribution 

I tested your changes via `{:kaffy, github: "arturictus/kaffy", branch: "update_phx"},`  for my project locally, and it works like a charm, even some known bugs in kaffy (like a bulk delete) were fixed.

maybe you should give a ping to https://github.com/aesmail/kaffy/issues/217 that now is solved 🤔

**Comment by arturictus** [comment]
Thanks @vermaxik, waiting for the new release.
I'm gonna ping the issue you mention.

**Comment by jeregrine** [comment]
I have tested this locally on a new install and it works.

**Comment by aesmail** [comment]
Appreciate the contribution!
It seems that multiple PRs included a fix for this.

**Pull request closed without merging**
