### PR TITLE
Initial support for custom types.

### PR DESCRIPTION
**Pull request by aesmail**
Warning: this is going to be a long description.

This PR provides early support for custom types.
This builds on top of ecto's [custom types](https://hexdocs.pm/ecto/Ecto.Type.html).

Kaffy requires two additional functions for the ecto custom types, `render_form/5` to specify how to render the custom type in the resource form page and `render_index/3` to specify how to render the field's value on the index page.

I have the following schema:
```elixir
schema "products" do
  field :url, MyApp.CustomURLField
end
```

This is how it is displayed in the form:
Screen Shot 2020-06-05 at 04 01 45

And this is how it is rendered in the index page (as a hyperlink):
Screen Shot 2020-06-05 at 04 02 31

This is how the custom field is defined (a bit longer than I would like tbh, most of it is necessary):
```elixir
defmodule Bakery.CustomURLField do
  use Ecto.Type
  def type, do: :string

  # casting input from the form and making it "storable" inside the database column (:string)
  def cast(url) when is_map(url) do
    IO.inspect(url)
    name = Map.get(url, "one")
    link = Map.get(url, "two")
    {:ok, ~s(<a href="#{link}">#{name}</a>)}
  end

  # if the input is not a string, return an error
  def cast(_), do: :error

  # loading the raw value from the database and turning it into a expected data type for the form
  def load(data) when is_binary(data) do
    [[_, link]] = Regex.scan(~r/href="(.*)"/, data)
    [[_, name]] = Regex.scan(~r/>(.*)</, data)

    {:ok, %{"one" => name, "two" => link}}
  end

  # this takes whatever the cast function gives it.
  # since we're only returning a string, which is the database field type, just save it as it is.
  def dump(url) when is_binary(url), do: {:ok, url}
  def dump(_), do: :error

  # this function should return the HTML related to rendering the customized form field.
  def render_form(_conn, changeset, form, field, _options) do
    [
      {:safe, ~s(<div class="form-group">)},
      Phoenix.HTML.Form.label(form, field, "Web URL"),
      Phoenix.HTML.Form.text_input(form, field,
        placeholder: "This is a custom field",
        class: "form-control",
        name: "#{form.name}[#{field}][one]",
        id: "#{form.name}_#{field}_one",
        value: get_field_value(changeset, field, "one")
      ),
      Phoenix.HTML.Form.text_input(form, field,
        placeholder: "This is a custom field",
        class: "form-control",
        name: "#{form.name}[#{field}][two]",
        id: "#{form.name}_#{field}_two",
        value: get_field_value(changeset, field, "two")
      ),
      {:safe, ~s(</div>)}
    ]
  end

  # this is how the field should be rendered on the index page
  def render_index(resource, field, _options) do
    case Map.get(resource, field) do
      nil ->
        ""

      details ->
        name = details["one"]
        link = details["two"]
        {:safe, ~s(<a href="#{link}">#{name}</a>)}
    end
  end

  defp get_field_value(changeset, field, subfield) do
    field_value = Map.get(changeset.data, field)
    Map.get(field_value || %{}, subfield, "")
  end
end
```

### CODE REVIEW

**Comment by aesmail** [comment]
@areski Your review is appreciated.
Also, I moved the jQuery script tag to the header of the layout so it can be potentially used in custom types.

**Comment by areski** [comment]
It does create an error with some previous working page.
For instance it expects render_index from Ecto type like `Ecto.UUID`

image

**Comment by aesmail** [comment]
Ah! Good catch. A fix is coming today.

**Comment by areski** [comment]
a possible fix here https://github.com/areski/kaffy/commit/a1460853eb07bc35c2f041a9e62ed3bdfb87a8c1

**Comment by aesmail** [comment]
Yup that's it 🙏🏻

**Comment by aesmail** [comment]
I think it's in a good "working" state right now.
We can add custom html, css, and javascript.

We could do some refactoring or behind the scene improvements, but other than that, I'm not sure how to improve this further for the end user.

Any ideas? How is it working for you?

**Comment by areski** [comment]
Sorry busy day today!
It's working well with your example indeed.

But yes it would be important to add some custom css/js, where would be the best place to put this ?

In django we do this by adding some HTML
https://github.com/areski/django-audiofield/blob/8599442d50d021b7b0483e9c1e4334f21f8fb75c/docs/source/includes/introduction.txt#L96

Is there a way we could inject header/footer into our template `new.html`, `show.html` & `index.html`?

**Comment by areski** [comment]
Yes I would agree, it's good working state now, we can improve from here

**Comment by aesmail** [comment]
Django is indeed more flexible with template blocks. I wish there was something similar in phoenix built-in. The issue with phoenix templates is, when you're inside a template, you can't write to some other template. This has to be from the controller before starting to render the template.

I think we have two options:

1. Add css and javascript inline with the custom html. I tested this and it works perfectly. I added some javascript validations to the two fields in the original comment and it worked as expected. This is the simplest option and it works now. The only technical downside I see here is that the javascript and the css tags will be added inside the form tag which is not "clean".
2. Find a way to collect all custom css/js and write it all at once in their respective locations (head/footer). This option might be more complicated. I'm not sure how to detect that honestly since currently Kaffy knows about the custom fields as it is rendering the form/index pages, not before.

**Comment by areski** [comment]
I can see how 2 would be complicated, maybe not worth it for now.

I have added a new issue, which *might* be worth exploring.
https://github.com/aesmail/kaffy/issues/82

Imagine that on the index I have a render that will use `progressbar.js` [https://www.npmjs.com/package/progressbar.js], I have many of those therefore I don't want for each element to add js/css.
It would be best in that case to have a way to define this globally

**Comment by aesmail** [comment]
This is how it's working now:

In configs we have:
```elixir
config :kaffy,
  otp_app: :my_app,
  # other settings
  extensions: [
    MyApp.KaffyExtensions.ExtensionOne,
    ThirdParty.Extensions.KaffyStyles,
  ]
```

Each extension module can have the following optional functions:

- `stylesheets/1`: This takes a `conn` and returns a list of `:safe` binaries to be included in the `<head>` section.
- `javascripts/1`: This also takes a `conn` and returns a list of `:safe` binaries to be included at the end just before the `</body>` tag.

Example:

```elixir
defmodule ThirdParty.Extensions.KaffyStyles do
  def stylesheets(_conn) do
    [
      {:safe, ~s(<link rel="stylesheet" href="https://example.com/css/styles.css" />)},
      {:safe, ~s(<link rel="stylesheet" href="/css/my-styles.css" />)},
    ]
  end

  def javascripts(_conn) do
    [
      {:safe, ~s(<script src="/js/scripts.js"></script>)}
    ]
  end
end
```

This would allow any arbitrary css or js to be included in Kaffy whether it's from the same application or from an external dependency.

This, along with custom field types, will allow developers to create and publish extensions for Kaffy.

I still feel like this needs to be more extensible. But so far I think we're heading in the right direction.

Thoughts?

**Comment by areski** [comment]
That looks pretty good, thanks for this!

**Comment by aesmail** [comment]
You're welcome. I like it.
The extension modules could also be used for a lot of other things in the future. I already have a few ideas I will share with you in the issues.

**Pull request merged**
