### PR TITLE
[fix](styles) fix processing of scss

### PR DESCRIPTION
**Pull request by areski**
This one has been itching my back for 2 weeks, so I finally take the time to learn how to work with scss.
Nice video about scss: https://www.youtube.com/watch?v=Zz6eOVaaelI
Extension for vscode: https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass

This will allow us to autocompile scss to a local css.

The goal here it's to embrace the scss we have from purpleadmin, and use them to work properly.
A lot of the changes in `kaffy.css` should at a later stage be moved to scss too.

I have added node_modules as there is only 2 libraries (bootstrap & compass-mixin), so other developer can directly work on kaffy without having to install those packages.

### CODE REVIEW

**Comment by aesmail** [comment]
Disclaimer: I don't fully understand how node_moduels and/or npm work. So the following is just based on "fear of not understanding" I guess.

I strongly feel like we shouldn't include node_modules in git.
It goes with the same reason why we shouldn't include the `deps` folder with elixir.
It might be ok for with just a couple libraries, but I feel it's going to be tricky and error-prone.

What if other developers clone the repo and run `npm i` and they download another version of those libraries and try to submit a PR? This would potentially create huge unnecessary changes to be included in the PR if they only changed 1 line of code.

I do see your point, but I'm not comfortable with the idea of node_modules being tracked. Maybe because I don't fully understand it. I've never liked dealing with node and npm since I feel they add unnecessary complexity if we're not using something already complex in the front end like react or angular, etc.

Also now that I think about it, what if we depend on node_modules but we don't include it, and people try to use kaffy (master) instead of the published version? Wouldn't they have to install the dependencies and compile the assets before running kaffy? Maybe the repo should only have already compiled files?

I would ask you to reconsider this, but if you think this is the better way, we'll merge it.

Having said all that, I do agree with you that we need to embrace sass after watching that video.

**Comment by areski** [comment]
I think we could have refused a PR that update `node_modules` the idea of having them there it's to speed up the developer job to have everything at hand to process the Scss, there is only bootstrap and compass-mixin, which should not be changing too often, but they might...
 
Thus I can argue against my own argument, by saying if the developer needs to install a VS plug-in, the can take 60 seconds to run 'npm install' :smile: 

I will follow your view on this, I think it's a valid point/fear.
So the PR has has node_modules  removed.

**Comment by areski** [comment]
@aesmail Ok with this?

**Comment by aesmail** [comment]
Yes definitely 👍🏼

**Pull request merged**
