### PR TITLE
Added support for actions map

### PR DESCRIPTION
**Pull request by Qizot**
My motivation for this pr was to enable dynamic creation of resource actions without leaking any atoms.

Currently `resource_actions` and `list_actions` have to be passed as keyword list therefore it enforces them to have limited amount of actions as each action has to be an atom. When you want to dynamically create the list you would have to apply `String.to_atom` for each action which might cause otp to reach atoms limit  when dealing with database stuff.

I suggest to keep the keyword list but also enable passing a map of actions that can be accessed by action type string.
e.g.
```elixir
    def resource_actions(_conn) do
      %{
        "action_name" => %{
          name: "Test Action",
          action: fn _, _ ->
            {:ok, %{}}
          end
        }
      }
    end
```

By doing so now we don't risk transforming "action_name" to a new atom and we can dynamically create the action based on received connection param.

The usecase I encountered by this is a situation where for `user` resource I can create add/remove role actions with their respective names fetched from database.

I also fixed old tests that didn't seem to pass anymore and added new tests for added feature.

### CODE REVIEW

**Comment by aesmail** [comment]
This is a very interesting PR @Qizot thanks a lot!
I dislike using atoms actually, but, when using them with keyword lists, they make it a bit easier to deal with in general.
However, the main reason I'm using keyword lists a lot in Kaffy instead of maps is, AFAIK, maps don't preserve their order while lists do. So the user sees the "actions" in the same order they are defined and you can easily re-order them.

Of course, this does make sense in some places and doesn't matter in others.
I still prefer maps if not for this minor issue to be honest.

What do you think?

**Comment by Qizot** [comment]
Yes, ordering the actions might be a problem, but we might as well introduce sorting by user defined `:index` field when defining action using maps and the reordering of the actions could happen in `Kaffy.ResourceAdmin.resource_actions(@my_resource, @conn)` function call if we detect a map instead of a list.
If user does not specify `:index` that would mean that he does not care about the order.

I mean, this use case might seem like a hack but it adds some flexibility and we still don't force the user to use maps. No breaking changes at all. But I don't if this feature is discoverable enough.

**Comment by Qizot** [comment]
Does it mean that we want to introduce `:index` field? :D I thing that I can create new pr even today.

**Comment by aesmail** [comment]
@Qizot yes please, but I'd use `:order` instead of `:index` to keep it similar to other kaffy options.

**Pull request merged**
